In [12]:
import numpy as np
np_array_1 = np.array([[1, 2, 3], [3, 4, 5]])
np_array_2 = np.array([[1, 2], [3, 4], [4, 5]])

In [13]:
print(np_array_1)

[[1 2 3]
 [3 4 5]]


In [14]:
print(np_array_2)

[[1 2]
 [3 4]
 [4 5]]


In [15]:
print(np.dot(np_array_1, np_array_2))

[[19 25]
 [35 47]]


In [16]:
print(np.dot(np_array_2, np_array_1))

[[ 7 10 13]
 [15 22 29]
 [19 28 37]]


In [4]:
a = np.array([[4,-1],[-5,3]])
b = np.array([1,2])
print(np.dot(a,b))

[2 1]


In [5]:
a = np.array([[3,4],[5,6]])
b = np.array([[1,-1],[-1,1]])
print(np.dot(a,b))

[[-1  1]
 [-1  1]]


$$
\begin{align}
\left\{
\begin{array}{ll}
x+y &= 2\\
2x+3y &= 5
\end{array}
\right.
\end{align}
$$

$$
\begin{eqnarray}
    x+y = 2 を2倍して\\
\end{eqnarray}
$$

$$
\begin{align}
\left\{
\begin{array}{ll}
2x+2y &= 4\\
2x+3y &= 5
\end{array}
\right.
\end{align}
$$

$$
\begin{eqnarray}
   &&(2x + 3y = 5) - (2x + 2y =4)より\\
   &&y = 1\\
   &&x+y = 2にy=1を代入して\\
   &&x=1\\
   &&よって、x=1 ,  y=1
\end{eqnarray}
$$

In [3]:
import numpy as np
mat = np.array([[1,1],[2,3]])
print("定義した行列\n",mat)
mat_inv = np.linalg.inv(mat)
print("逆行列\n",mat_inv)
a = np.array([2,5])
print("答え\n",np.dot(mat_inv, a))

定義した行列
 [[1 1]
 [2 3]]
逆行列
 [[ 3. -1.]
 [-2.  1.]]
答え
 [1. 1.]
